import { AppShell, Box, Text } from "@mantine/core/"
import Head from "next/head"
import MixJuiceHeader from "@/components/MixJuiceHeader"
import MixJuiceNavbar from "@/components/MixJuiceNavbar"

export default function Home() {
  return (
    <>
      <Head>
        <title>MixJuice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppShell header={<MixJuiceHeader />} navbar={<MixJuiceNavbar />}>
          <Box>メインコンテンツ</Box>
          <Text>フォントチェック</Text>
          <Text>Font Check</Text>
          <Text>Alphabetと日本語のミックス</Text>
        </AppShell>
      </main>
    </>
  )
}
