import { Box, Text } from "@mantine/core/"
import Head from "next/head"
import Layout from "@/components/layouts/Layout"
import Player from "@/components/templates/Player"

export default function Home() {
  return (
    <>
      <Head>
        <title>MixJuice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Box w="100%" h={{ base: "15vh", md: "25vh" }}>
          <Player />
        </Box>

        <Box>メインコンテンツ</Box>
        <Text>フォントチェック</Text>
        <Text>Font Check</Text>
        <Text>Alphabetと日本語のミックス</Text>
      </Layout>
    </>
  )
}
