import { Box, Text } from "@mantine/core/"
import Head from "next/head"
import Layout from "@/components/layouts/Layout"
import MusicList from "@/components/templates/MusicList"
import Player from "@/components/templates/Player"
import useBreakPoints from "@/hooks/useBreakPoints"

const Main = () => {
  const { breakPoint, setRespVal } = useBreakPoints()

  return (
    <>
      <Head>
        <title>MixJuice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Box w="100%" h={setRespVal("15vh", "25vh", "25vh")}>
          <Player />
        </Box>

        <Box w="100%" pt="md">
          <MusicList />
        </Box>

        <Box p="md">
          <Box>メインコンテンツ</Box>
          <Text>フォントチェック</Text>
          <Text>Font Check</Text>
          <Text>Alphabetと日本語のミックス</Text>
          {breakPoint}
        </Box>
      </Layout>
    </>
  )
}

export default Main
